### ISSUE TITLE
glass bottle consumed when creating dough

### ISSUE THREAD

**Issue by Redd56** [Miros77/Realistic-Bakery-Products---Fabric#1]
when creating dough, the glass bottle you use to make it is consumed, i believe that would mean i am eating cooked glass...

**Comment by Miros77** [comment]
![Снимок](https://user-images.githubusercontent.com/59547044/95860377-a7ecb580-0d68-11eb-8e5b-7410650297a2.PNG)
HERE'S A NEW CRAFT

**Comment by Miros77** [comment]
HERE'S A NEW CRAFT
![Снимок](https://user-images.githubusercontent.com/59547044/95880014-b2ff1000-0d7f-11eb-9eb6-c6d01b2b68b4.PNG)

**Comment by Miros77** [comment]
I will close this problem????

**Comment by Miros77** [comment]
![Uploading ОО.png…]()

**Comment by Miros77** [comment]
![ОО](https://user-images.githubusercontent.com/59547044/95900343-6aa11b80-0d9a-11eb-946c-74ca32929f09.png)

**Comment by Miros77** [comment]
fixed 1.1.4.2

**Comment by Miros77** [comment]
> when creating dough, the glass bottle you use to make it is consumed, i believe that would mean i am eating cooked glass...

thank you
