### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by Water-Kitten** [Miros77/Realistic-Bakery-Products---Fabric#4]
Hi Miros !

As you asked me to, I made a french translation of your mod. Can you explain me how we're supposed to used the "pull requests" to add it please ? I want to know how to do it by myself for later translations of other mods. Thank you !

**Comment by Miros77** [comment]
I'll explain now

**Comment by Miros77** [comment]
![image](https://user-images.githubusercontent.com/59547044/96767091-b5e3ab80-13e4-11eb-80a1-4e972da39f9e.png)

**Comment by Miros77** [comment]
and add the fr_fr.json file

**Comment by Miros77** [comment]
![image](https://user-images.githubusercontent.com/59547044/96772364-b469b180-13eb-11eb-922f-eeb91811d296.png)
you are on Twitch?

**Comment by Water-Kitten** [comment]
![image](https://user-images.githubusercontent.com/70285608/96878009-a2831f80-147a-11eb-91c9-2d6230bae581.png)
 I followed your instructions and it's shows me this. What am I supposed to do now? '-'

And no sorry, I nearly never use Twitch, why ?

**Comment by Miros77** [comment]
> ![image](https://user-images.githubusercontent.com/70285608/96878009-a2831f80-147a-11eb-91c9-2d6230bae581.png)
> I followed your instructions and it's shows me this. What am I supposed to do now? '-'
> 
> And no sorry, I nearly never use Twitch, why ?

I'll fix it now

**Comment by Miros77** [comment]
you can check
https://github.com/Miros77/Realistic-Bakery-Products---Fabric/tree/master/src/main/resources/assets/realistic_bakery_products/lang

**Comment by Water-Kitten** [comment]
Done, thank you dude !

Tell me if you want any change

**Comment by Miros77** [comment]
> Done, thank you dude !
> 
> Tell me if you want any change

Yes

**Comment by Miros77** [comment]
thanks for the translation/merci pour la traduction

**Comment by Miros77** [comment]
what is your Twitch username? I will add you to the page!

**Comment by Water-Kitten** [comment]
Paton666, but I don't really use Twitch really ofen, and your welcome !

**Comment by Miros77** [comment]
![image](https://user-images.githubusercontent.com/59547044/97062455-a363a080-15a3-11eb-9165-54a31c1931d4.png)

**Comment by Water-Kitten** [comment]
Thx !

**Comment by Miros77** [comment]
Please translate

     //NEW   
  //Item  
  "item.realistic_bakery_products.bread_slice": "Bread Slice",
  "item.realistic_bakery_products.golden_knife": "Golden Knife",
  "item.realistic_bakery_products.golden_spoon": "Golden Spoon",
  "item.realistic_bakery_products.iron_knife": "Iron Knife",
  "item.realistic_bakery_products.iron_spoon": "Iron Spoon",
  "item.realistic_bakery_products.cake_base": "Cake Base",
  "item.realistic_bakery_products.raw_chocolate_shortcake": "Raw Chocolate Shortcake",
  "item.realistic_bakery_products.raw_bread_slice": "Raw Bread Slice",
  "item.realistic_bakery_products.honey_dough": "Honey Dough",
  "item.realistic_bakery_products.raw_flatbread": "Raw Flatbread",
  "item.realistic_bakery_products.raw_new_bread": "Raw Big Bread",
  "item.realistic_bakery_products.new_bread": "Big Bread",
  "item.realistic_bakery_products.raw_cheese_flatbread": "Raw Cheese Flatbread",
  "item.realistic_bakery_products.cheese_flatbread": "Cheese Flatbread",

//Block
"item.realistic_bakery_products.raw_bread_block": "Raw Bread",
"item.realistic_bakery_products.bread_block": "Bread"

**Comment by Miros77** [comment]
> Thx !

Please translate

**Comment by Water-Kitten** [comment]
At your service, Sir !

`---------------------------------------------------------------------------------` 
> //Item
> "item.realistic_bakery_products.bread_slice": "Tranche de Pain",
> "item.realistic_bakery_products.golden_knife": "Couteau en Or",
> "item.realistic_bakery_products.golden_spoon": "Cuillière en Or",
> "item.realistic_bakery_products.iron_knife": "Couteau en Fer",
> "item.realistic_bakery_products.iron_spoon": "Cuillère en Fer",
> "item.realistic_bakery_products.cake_base": "Base de Gâteau",
> "item.realistic_bakery_products.raw_chocolate_shortcake": "Biscuit au Chocolat Cru",
> "item.realistic_bakery_products.raw_bread_slice": "Tranche de Pain Crue",
> "item.realistic_bakery_products.honey_dough": "Pâte au Miel",
> "item.realistic_bakery_products.raw_flatbread": "Pâte à Pizza Crue",
> "item.realistic_bakery_products.raw_new_bread": "Miche de Pain Crue",
> "item.realistic_bakery_products.new_bread": "Miche de Pain",
> "item.realistic_bakery_products.raw_cheese_flatbread": "Pâte à Pizza au Fromage Crue",
> "item.realistic_bakery_products.cheese_flatbread": "Pâte à Pizza au Fromage",
> 
> //Block
> "item.realistic_bakery_products.raw_bread_block": "Pain Cru",
> "item.realistic_bakery_products.bread_block": "Pain"

`---------------------------------------------------------------------------------`

**Comment by Miros77** [comment]
> At your service, Sir !
> 
> `---------------------------------------------------------------------------------`
> 
> > //Item
> > "item.realistic_bakery_products.bread_slice": "Tranche de Pain",
> > "item.realistic_bakery_products.golden_knife": "Couteau en Or",
> > "item.realistic_bakery_products.golden_spoon": "Cuillière en Or",
> > "item.realistic_bakery_products.iron_knife": "Couteau en Fer",
> > "item.realistic_bakery_products.iron_spoon": "Cuillère en Fer",
> > "item.realistic_bakery_products.cake_base": "Base de Gâteau",
> > "item.realistic_bakery_products.raw_chocolate_shortcake": "Biscuit au Chocolat Cru",
> > "item.realistic_bakery_products.raw_bread_slice": "Tranche de Pain Crue",
> > "item.realistic_bakery_products.honey_dough": "Pâte au Miel",
> > "item.realistic_bakery_products.raw_flatbread": "Pâte à Pizza Crue",
> > "item.realistic_bakery_products.raw_new_bread": "Miche de Pain Crue",
> > "item.realistic_bakery_products.new_bread": "Miche de Pain",
> > "item.realistic_bakery_products.raw_cheese_flatbread": "Pâte à Pizza au Fromage Crue",
> > "item.realistic_bakery_products.cheese_flatbread": "Pâte à Pizza au Fromage",
> > //Block
> > "item.realistic_bakery_products.raw_bread_block": "Pain Cru",
> > "item.realistic_bakery_products.bread_block": "Pain"
> 
> `---------------------------------------------------------------------------------`

Thanks!

**Comment by Miros77** [comment]
//Change
 "item.realistic_bakery_products.raw_new_bread": "Raw Bread",
 "item.realistic_bakery_products.new_bread": "Bread",

//NEW   
//Item 
 "item.realistic_bakery_products.raw_sausage": "Raw Sausage",
 "item.realistic_bakery_products.sausage_slice": "Sausage Slice",
 "item.realistic_bakery_products.sausage_slice_9": "9 Sausage Slice",
 "item.realistic_bakery_products.sausage_slice_15": "15 Sausage Slice",
 "item.realistic_bakery_products.brown_mushroom_7": "7 Brown Mushroom",
 "sausage_slice_15.realistic_bakery_products.tooltip": "Ingredients for Pizza",
 //Block
 "block.realistic_bakery_products.sausage_block": "Sausage"

**Comment by Miros77** [comment]
> Thx !

Please translate!

**Comment by Water-Kitten** [comment]
Done!

`---------------------------------------------------------------------------------`

> //Change
> "item.realistic_bakery_products.raw_new_bread": "Miche de pain cru",
> "item.realistic_bakery_products.new_bread": "Miche de pain",
> 
> //NEW
> //Item
> "item.realistic_bakery_products.raw_sausage": "Saucisse crue",
> "item.realistic_bakery_products.sausage_slice": "Tranche de saucisse",
> "item.realistic_bakery_products.sausage_slice_9": "9 Tranches de saucisse",
> "item.realistic_bakery_products.sausage_slice_15": "15 Tranches de saucisse",
> "item.realistic_bakery_products.brown_mushroom_7": "7 Champignons bruns",
> "sausage_slice_15.realistic_bakery_products.tooltip": "Ingrédients pour pizza",
> //Block
> "block.realistic_bakery_products.sausage_block": "Saussice"

`---------------------------------------------------------------------------------`

**Comment by Miros77** [comment]
> Done!
> 
> `---------------------------------------------------------------------------------`
> 
> > //Change
> > "item.realistic_bakery_products.raw_new_bread": "Miche de pain cru",
> > "item.realistic_bakery_products.new_bread": "Miche de pain",
> > //NEW
> > //Item
> > "item.realistic_bakery_products.raw_sausage": "Saucisse crue",
> > "item.realistic_bakery_products.sausage_slice": "Tranche de saucisse",
> > "item.realistic_bakery_products.sausage_slice_9": "9 Tranches de saucisse",
> > "item.realistic_bakery_products.sausage_slice_15": "15 Tranches de saucisse",
> > "item.realistic_bakery_products.brown_mushroom_7": "7 Champignons bruns",
> > "sausage_slice_15.realistic_bakery_products.tooltip": "Ingrédients pour pizza",
> > //Block
> > "block.realistic_bakery_products.sausage_block": "Saussice"
> 
> `---------------------------------------------------------------------------------`

THX

**Comment by Miros77** [comment]
Please translate!

  //1.1.7
  "item.realistic_bakery_products.milk_bun": "Milk Bun",
  "item.realistic_bakery_products.milk_dough": "Milk Dough",
  "item.realistic_bakery_products.cocoa_dust": "Cocoa",

   //Tooltip 
  "knife.realistic_bakery_products.tooltip": "Use a Knife to cut: Cheese Block, Sausage, Bread, Raw Bread",
  "spoon.realistic_bakery_products.tooltip": "Use Spoon to eat all cakes except regular cake (works on raw cake)",

  "get_flour.realistic_bakery_products.tooltip": "To get Flour put Wheat in the Mill",
  "get_cocoa.realistic_bakery_products.tooltip": "To get Cocoa put Cocoa Beans in the Mill",

  "bread_slice.realistic_bakery_products.tooltip": "To get a Bread Slice , press the Bread Block with a knife",
  "raw_bread_slice.realistic_bakery_products.tooltip": "To get a Raw Bread Slice  press the knife On the Raw Bread Block",  
  "сheese_slice.realistic_bakery_products.tooltip": "To get a Sausage Slice  press the knife On the Sausage Block",
  "sausage_slice.realistic_bakery_products.tooltip": "To get a Cheese Slice  press the knife On the Cheese Block"

**Comment by Miros77** [comment]
> Done!
> 
> `---------------------------------------------------------------------------------`
> 
> > //Change
> > "item.realistic_bakery_products.raw_new_bread": "Miche de pain cru",
> > "item.realistic_bakery_products.new_bread": "Miche de pain",
> > //NEW
> > //Item
> > "item.realistic_bakery_products.raw_sausage": "Saucisse crue",
> > "item.realistic_bakery_products.sausage_slice": "Tranche de saucisse",
> > "item.realistic_bakery_products.sausage_slice_9": "9 Tranches de saucisse",
> > "item.realistic_bakery_products.sausage_slice_15": "15 Tranches de saucisse",
> > "item.realistic_bakery_products.brown_mushroom_7": "7 Champignons bruns",
> > "sausage_slice_15.realistic_bakery_products.tooltip": "Ingrédients pour pizza",
> > //Block
> > "block.realistic_bakery_products.sausage_block": "Saussice"
> 
> `---------------------------------------------------------------------------------`

Please translate!

**Comment by Water-Kitten** [comment]
For you, Dear~

`---------------------------------------------------------------------------------`

> 
> //1.1.7
> "item.realistic_bakery_products.milk_bun": "Brioche",
> "item.realistic_bakery_products.milk_dough": "Pâte à brioche",
> "item.realistic_bakery_products.cocoa_dust": "Cacao",
> 
> //Tooltip
> "knife.realistic_bakery_products.tooltip": "Utiliser un couteau pour couper: Morceau de fromage, Saucisse, Pain, Pain cru",
> "spoon.realistic_bakery_products.tooltip": "Utiliser une cuillère pour manger tout les gâteaux à l'exception du Gâteau simple (fonctionne aussi sur les gâteaux crus)",
> 
> "get_flour.realistic_bakery_products.tooltip": "Pour obtenir de la Farine, mettre du Blé dans le Moulin.",
> "get_cocoa.realistic_bakery_products.tooltip": "Pour obtenir du Cacao, mettre des Fèves de cacao dans le Moulin.",
> 
> "bread_slice.realistic_bakery_products.tooltip": "Pour obtenir une Tranche de pain, interargir sur un Pain avec un Couteau.",
> "raw_bread_slice.realistic_bakery_products.tooltip": "Pour obtenir une Tranche de pain crue, interargir sur un Pain cru avec un Couteau.",
> "сheese_slice.realistic_bakery_products.tooltip": "Pour obtenir une Tranche de saucisse, interargir sur une Saucisse avec un Couteau.",
> "sausage_slice.realistic_bakery_products.tooltip": "Pour obtenir une Tranche de fromage, interargir sur un Morceau de fromage avec un Couteau."

`---------------------------------------------------------------------------------`

**Comment by Miros77** [comment]
Thanks!

**Comment by Miros77** [comment]
HI Please translate!

//1.3.0
"item.realistic_bakery_products.rolling_pin": "Rolling Pin",
"item.realistic_bakery_products.hand_mill": "Hand Mill",
"item.realistic_bakery_products.hand_mill_wooden_funnel": "wooden Funnel",
"item.realistic_bakery_products.hand_mill_crank": "Crank",
"item.realistic_bakery_products.hand_mill_millstone": "Millstone",

**Comment by Water-Kitten** [comment]
Here you go, my friend !

> //1.3.0
> "item.realistic_bakery_products.rolling_pin": "Rouleau à pâtisserie",
> "item.realistic_bakery_products.hand_mill": "Moulin à grain manuel",
> "item.realistic_bakery_products.hand_mill_wooden_funnel": "Entonnoir en bois",
> "item.realistic_bakery_products.hand_mill_crank": "Manivelle",
> "item.realistic_bakery_products.hand_mill_millstone": "Meule",

**Comment by Miros77** [comment]
Thanks !
