### ISSUE TITLE
Doughnuts

### ISSUE THREAD

**Issue by RaveIV** [Miros77/Realistic-Bakery-Products---Fabric#9]
Hello,

So I'm using the 1.17 mod and for some reason donuts don't seem to show up as a craftable item based on the recipe displayed on the mod. I may just be doing something wrong, but after reading the comments I DID manage to craft the dough with the use of a stone cutter on the wheat to make flour. But while the raw bread pops up as craftable, the doughnut doesn't seem to. Any help/insight would be highly appreciated! Thank you! :)

-Rave

**Comment by Miros77** [comment]
try using milk dough in crafting

**Comment by Miros77** [comment]
Try the new version of the mod 1.3.0 1.17
https://www.curseforge.com/minecraft/mc-mods/realistic-bakery-products-fabric/files/all
